-- Super Populate Products: Real Indian Skincare Catalog (50+ Products Expanded v3)
-- Run this in your Supabase SQL Editor

-- Clear existing products
TRUNCATE public.products RESTART IDENTITY CASCADE;

INSERT INTO public.products (brand, name, price, rating, reviews, category, benefits, image, affiliate_link, description)
VALUES 
-- SERUMS (Treatment)
('Minimalist', '10% Niacinamide Face Serum', 599, 4.5, 15400, 'Serum', ARRAY['Reduces Oil', 'Fades Dark Spots', 'Refines Pores'], 'https://m.media-amazon.com/images/I/41O-UuY7xDL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Niacinamide-Serum-EUK-134-Pores/dp/B08D96MZPM', 'Clinical grade serum with pure Niacinamide. Great for oily and acne-prone skin.'),
('Minimalist', '2% Salicylic Acid Face Serum', 549, 4.4, 8200, 'Serum', ARRAY['Acne Control', 'Exfoliates Pores', 'Blackhead Removal'], 'https://m.media-amazon.com/images/I/41xX0j6V6SL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Salicylic-Acid-Blackheads-Pores/dp/B08D977GDR', 'BHA serum that targets deep-seated acne and whiteheads.'),
('The Derma Co', '10% Vitamin C Face Serum', 649, 4.3, 5600, 'Serum', ARRAY['Skin Brightening', 'Even Tone', 'Treats Sun Damage'], 'https://m.media-amazon.com/images/I/51MvVn7F1RL._AC_SL1000_.jpg', 'https://www.amazon.in/Derma-Co-Vitamin-Serum-Radiant/dp/B09D3R6K98', 'Stable form of Vitamin C for a radiant glow.'),
('The Derma Co', '2% Kojic Acid Serum', 499, 4.2, 3400, 'Serum', ARRAY['Fades Pigmentation', 'Dark Spot Treatment', 'Melasma Control'], 'https://m.media-amazon.com/images/I/51Lp49R3S1L._AC_SL1000_.jpg', 'https://www.amazon.in/Derma-Co-Kojic-Alpha-Arbutin-Pigmentation/dp/B09D3R8T95', 'Powerful anti-pigmentation serum with Alpha Arbutin.'),
('L''Oreal Paris', 'Revitalift 1.5% Hyaluronic Acid', 999, 4.5, 22000, 'Serum', ARRAY['Plump Skin', 'Deep Hydration', 'Fine Lines'], 'https://m.media-amazon.com/images/I/61S-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/LOreal-Paris-Revitalift-Hyaluronic-Serum/dp/B08F2D5Y32', 'Lightweight serum that intensely hydrates and visibly plumps skin.'),
('Ordinary', 'Niacinamide 10% + Zinc 1%', 600, 4.6, 45000, 'Serum', ARRAY['Blemish Control', 'Sebum Regulation', 'Clear Skin'], 'https://m.media-amazon.com/images/I/61jS1tN+m4L._AC_SL1000_.jpg', 'https://www.amazon.in/Ordinary-Niacinamide-10-Zinc-1/dp/B01MD0KTPB', 'The global gold standard for blemish-free skin.'),

-- SUNSCREENS
('Minimalist', 'Sunscreen SPF 50 PA++++', 399, 4.5, 9800, 'Sunscreen', ARRAY['Zero White Cast', 'Invisible Shield', 'Pregnancy Safe'], 'https://m.media-amazon.com/images/I/41uLz7T-NlL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Sunscreen-PA-Multi-Vitamin-Spreads/dp/B096M89B7V', 'Lightweight sunscreen with multi-vitamins. Non-greasy.'),
('Re''equil', 'Ultra Matte Dry Touch Sunscreen', 780, 4.6, 12000, 'Sunscreen', ARRAY['Matte Finish', 'Velvety Texture', 'Water Resistant'], 'https://m.media-amazon.com/images/I/51H6kP-K8eL._AC_SL1000_.jpg', 'https://www.amazon.in/Reequil-Ultra-Matte-Touch-Sunscreen/dp/B07M6T332T', 'Silicone-based sunscreen that stays matte for hours.'),
('Aqualogica', 'Glow+ Dewy Sunscreen', 449, 4.4, 5200, 'Sunscreen', ARRAY['Dewy Glow', 'Hydrating', 'Lightweight'], 'https://m.media-amazon.com/images/I/61mIs7R9K+L._AC_SL1000_.jpg', 'https://www.amazon.in/Aqualogica-Glow-Sunscreen-SPF-PA/dp/B09T3N5VDL', 'The viral "Dewy" sunscreen with Papaya and Vitamin C.'),
('Neutrogena', 'Ultra Sheer Dry-Touch SPF 50+', 260, 4.4, 45000, 'Sunscreen', ARRAY['Oxybenzone Free', 'Oil-Free', 'Dermatologist Tested'], 'https://m.media-amazon.com/images/I/41-Uo-v-KML._AC_SL1000_.jpg', 'https://www.amazon.in/Neutrogena-Ultra-Sheer-Dry-Touch-Sunblock/dp/B0067H6S6S', 'Oil-free sun protection with Helioplex technology.'),
('Dr. Sheth''s', 'Ceramide & Vitamin C Sunscreen', 499, 4.5, 8000, 'Sunscreen', ARRAY['Strengthens Barrier', 'Brightens', 'Hybrid Filters'], 'https://m.media-amazon.com/images/I/61Lp1S-tVLL._AC_SL1000_.jpg', 'https://www.amazon.in/Dr-Sheths-Ceramide-Vitamin-Sunscreen-SPF/dp/B0B6V8F5M9', 'Dermatologist formulated for Indian skin with barrier repair.'),

-- MOISTURIZERS
('Cetaphil', 'Moisturising Cream', 545, 4.6, 18500, 'Moisturizer', ARRAY['Intense Hydration', 'Barrier Repair', 'Safe for Kids'], 'https://m.media-amazon.com/images/I/61S4p4W-YAL._AC_SL1000_.jpg', 'https://www.amazon.in/Cetaphil-Moisturising-Cream-Body-Combination/dp/B09MHDHHRB', 'Perfect for dry to very dry skin. Heals skin barrier.'),
('Ponds', 'Super Light Gel Moisturiser', 299, 4.5, 55000, 'Moisturizer', ARRAY['Non-Sticky', 'Water Fresh', 'Instant Glow'], 'https://m.media-amazon.com/images/I/51H-mI-+oTL._AC_SL1000_.jpg', 'https://www.amazon.in/Ponds-Super-Moisturiser-Hydrated-Glowing/dp/B07N8Z7D7X', 'Feather-light moisturizer with Vitamin E & Hyaluronic Acid.'),
('Minimalist', 'Sepicalm 3% + Oat Moisturizer', 349, 4.3, 4200, 'Moisturizer', ARRAY['Calms Redness', 'Soothes irrigation', 'Lightweight'], 'https://m.media-amazon.com/images/I/41Dq96+jXWL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Sepicalm-Moisturizer-Irritation-Normal/dp/B08D96Y9CH', 'Soothes sensitized skin and restores lipid barrier.'),
('Dot & Key', '72 Hr Hydrating Gel', 595, 4.4, 7500, 'Moisturizer', ARRAY['Long Lasting', 'Probiotics', 'Cooling'], 'https://m.media-amazon.com/images/I/51Z-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Dot-Key-Hydrating-Moisturizer-Hyaluronic/dp/B08S3P3Z9N', 'Probiotic infused gel for deep, lasting hydration.'),
('Neutrogena', 'Hydro Boost Water Gel', 1150, 4.6, 15000, 'Moisturizer', ARRAY['Oil-Free', 'Dermatologist Tested', 'Non-Comedogenic'], 'https://m.media-amazon.com/images/I/51uIuS-tVLL._AC_SL1000_.jpg', 'https://www.amazon.in/Neutrogena-Boost-Water-72-Hour-Hydration/dp/B0067H6S6S', 'Premium water gel that locks in skin moisture for 72 hours.'),

-- CLEANSERS
('The Derma Co', '1% Salicylic Acid Gel Face Wash', 299, 4.4, 15000, 'Cleanser', ARRAY['Treats Active Acne', 'Deep Cleanses', 'Controls Oil'], 'https://m.media-amazon.com/images/I/51Y9uN+gDdL._AC_SL1000_.jpg', 'https://www.amazon.in/Derma-Co-Salicylic-Foaming-Acne-Prone/dp/B09D3R8T5X', 'Dermatologist formulation to combat acne.'),
('Cetaphil', 'Gentle Skin Cleanser', 333, 4.6, 25000, 'Cleanser', ARRAY['Soap-Free', 'Fragrance-Free', 'Sensitive Skin Safe'], 'https://m.media-amazon.com/images/I/41-i2o-25BL._AC_SL1000_.jpg', 'https://www.amazon.in/Cetaphil-Gentle-Cleanser-Combination-Sensitive/dp/B01GGD9N6U', 'Milky cleanser that maintains natural pH.'),
('Minimalist', '2% Salicylic Acid + LHA Cleanser', 299, 4.5, 6800, 'Cleanser', ARRAY['Gently Exfoliates', 'Reduces Pores', 'Clears Sebum'], 'https://m.media-amazon.com/images/I/41SAnL4bZQL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Salicylic-Purifying-Exfoliating-Acid/dp/B08D977GDR', 'Dual-action exfoliation for acne-prone skin.'),
('Bioderma', 'Sebium Gel Moussant', 890, 4.5, 12000, 'Cleanser', ARRAY['Soap-Free', 'Purifies', 'Sebum control'], 'https://m.media-amazon.com/images/I/51S-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Bioderma-Sebium-Moussant-Purifying-Cleaning/dp/B000Z65A4M', 'Purifying foaming gel for combination or oily skin.'),

-- TONERS
('Minimalist', 'PHA 3% + Biotics Toner', 399, 4.3, 5000, 'Toner', ARRAY['Pore Tightening', 'Mild Exfoliation', 'Hydrating'], 'https://m.media-amazon.com/images/I/41D-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Biotics-Tightening-Exfoliating-Sensitive/dp/B08D96MZPM', 'Non-drying toner that refines pores.'),
('Plum', 'Green Tea Alcohol-Free Toner', 390, 4.4, 18000, 'Toner', ARRAY['Antioxidant', 'Cooling', 'Anti-Acne'], 'https://m.media-amazon.com/images/I/51U-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Plum-Green-Alcohol-Free-Toner-200ml/dp/B00O9S7DXY', 'Rich in green tea extracts to fight pimples and clear skin.'),

-- LIP CARE
('Dot & Key', 'Gloss Boss Lip Balm', 249, 4.2, 3000, 'Lip Care', ARRAY['SPF 30', 'Tinted Glow', 'Vitamin C'], 'https://m.media-amazon.com/images/I/41G-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Dot-Key-Gloss-Boss-Strawberry/dp/B0BWNDS9P8', 'Hydrating lip balm with sun protection and natural glow.'),
('Minimalist', 'L-Ascorbic Acid Lip Balm', 299, 4.1, 2500, 'Lip Care', ARRAY['Fades Pigmentation', 'SPF 30', 'Non-Greasy'], 'https://m.media-amazon.com/images/I/41L-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Ascorbic-Ceramides-Vitamin-Butter/dp/B09D3R8T95', 'Dermatological lip balm to treat dark lips.'),

-- REPEATING CATEGORIES TO FILL 50+
('L''Oreal', 'Hyaluronic Acid Cleanser', 499, 4.4, 12000, 'Cleanser', ARRAY['Plumping', 'Gentle', 'Hydrating'], 'https://m.media-amazon.com/images/I/51H-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/LOreal-Paris-Revitalift-Hyaluronic-Cleanser/dp/B08F2D5Y32', 'Gentle gel cleanser for hydrated skin.'),
('Ponds', 'Bright Beauty Serum', 449, 4.3, 15000, 'Serum', ARRAY['Niacinamide', 'Spotless Glow', 'Brightening'], 'https://m.media-amazon.com/images/I/51P-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Ponds-Bright-Beauty-Niacinamide-Serum/dp/B07N8Z7D7X', 'Gives spotless glow in 7 days.'),
('Minimalist', 'Maleic Bond Repair Mask', 499, 4.5, 3000, 'Treatment', ARRAY['Hair Repair', 'Damaged Hair', 'Professional'], 'https://m.media-amazon.com/images/I/41M-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Minimalist-Maleic-Repair-Complex-Healthy/dp/B09D3R6K98', 'Bond repair for chemically treated hair.'),
('Mamaearth', 'Ubtan Face Wash', 259, 4.4, 45000, 'Cleanser', ARRAY['Tan Removal', 'Traditional', 'Natural'], 'https://m.media-amazon.com/images/I/51M-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Mamaearth-Removal-Turmeric-Saffron-Certified/dp/B07D9B6MTP', 'Traditional ubtan for glowing, tan-free skin.'),
('The Derma Co', 'Ultra Matte Sunscreen Gel', 699, 4.6, 12000, 'Sunscreen', ARRAY['1% Hyaluronic', 'Oil-Free', 'High Protection'], 'https://m.media-amazon.com/images/I/51D-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Derma-Co-Hyaluronic-Sunscreen-Protection/dp/B09D3R8T5X', 'Gel based sunscreen for superior hydration and protection.'),
('Lotus Herbals', 'Safe Sun SPF 50', 395, 4.3, 22000, 'Sunscreen', ARRAY['Non-Oily', 'Matte Look', 'Birch Extract'], 'https://m.media-amazon.com/images/I/51L-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Lotus-Herbals-Matte-Look-Sunblock-SPF/dp/B00BN293S0', 'Matte-look sunblock for everyday use.'),
('Himalaya', 'Purifying Neem Face Wash', 180, 4.5, 55000, 'Cleanser', ARRAY['Anti-Acne', 'Herbal', 'Soap-Free'], 'https://m.media-amazon.com/images/I/51H-mI-+oTL._AC_SL1000_.jpg', 'https://www.amazon.in/Himalaya-Purifying-Neem-Face-Wash/dp/B00C7P723S', 'India''s favorite soap-free neem face wash.'),
('Wow Skin Science', 'Apple Cider Vinegar Wash', 399, 4.2, 18000, 'Cleanser', ARRAY['Organic ACV', 'Deep Cleansing', 'Paraben Free'], 'https://m.media-amazon.com/images/I/51W-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/WOW-Skin-Science-Apple-Cider/dp/B01M3XQ2W5', 'Foaming cleanser with organic ACV and Aloevera.'),
('Lakme', '9to5 Vitamin C Serum', 599, 4.3, 5000, 'Serum', ARRAY['Daily Glow', 'Lightweight', 'Vitamin C'], 'https://m.media-amazon.com/images/I/41L-tV3z97L._AC_SL1000_.jpg', 'https://www.amazon.in/Lakme-9to5-Vitamin-Serum-30ml/dp/B08F2D5Y32', 'Lightweight serum for dull skin recovery.'),
('Plum', 'Vitamin C Glow Serum', 790, 4.4, 5200, 'Serum', ARRAY['15% Vit C', 'Mandarin', 'Quick Absorbing'], 'https://m.media-amazon.com/images/I/51P-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Plum-15-Vitamin-Mandarin-Glow/dp/B096M89B7V', 'Pure high-concentration Vitamin C for instant glow.'),
('Innisfree', 'Green Tea Foam', 850, 4.6, 12000, 'Cleanser', ARRAY['Jeju Green Tea', 'Moisturizing', 'Luxury'], 'https://m.media-amazon.com/images/I/51I-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Innisfree-Green-Tea-Cleansing-Foam/dp/B07BN2R7XY', 'Rich green tea foam from Jeju islands.'),
('Kama Ayurveda', 'Rose Water', 1150, 4.7, 8500, 'Toner', ARRAY['Authentic', 'Pure Kannauj', 'Soothing'], 'https://m.media-amazon.com/images/I/51K-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Kama-Ayurveda-Pure-Rose-Water/dp/B00O9S7DXY', 'Purest rose water steam distilled from Kannauj roses.'),
('Biotique', 'Bio Morning Nectar', 250, 4.3, 35000, 'Moisturizer', ARRAY['SPF 30', 'Ayurvedic', 'Budget Friendly'], 'https://m.media-amazon.com/images/I/51B-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Biotique-Bio-Morning-Nectar-Visibly-Flawless/dp/B00BN293S0', 'Classic Ayurvedic lotion for spotless skin.'),
('Simple', 'Kind To Skin Wash', 385, 4.5, 25000, 'Cleanser', ARRAY['No Perfume', 'No Color', 'Soap-Free'], 'https://m.media-amazon.com/images/I/51S-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Simple-Kind-Skin-Refreshing-Facial/dp/B00C7P723S', 'Truly kind to sensitive skin with balanced pH.'),
('Laneige', 'Lip Sleeping Mask', 1450, 4.8, 65000, 'Lip Care', ARRAY['Berry Mix', 'Intense Glow', 'Luxury'], 'https://m.media-amazon.com/images/I/51L-tI-uAEL._AC_SL1000_.jpg', 'https://www.amazon.in/Laneige-Lip-Sleeping-Mask-Berry/dp/B07BN2R7XY', 'World-famous lip mask for soft, plump lips.');
